### ISSUE TITLE
how could i overwrite the same dir 's files

### ISSUE THREAD

**Issue by cdll** [qiu8310/grunt-deploy-asset#1]
如题，如何配置DA以支持outDir和rootDir相同的时候upload完成后返回来的文件覆盖rootDir目录下的已有文件。
我的开发源文件在src下，grunt打包后生成的文件在build下，然后我再以build作为DA的rootDir进行DA task的。
当我配置rootDir为src的时候是是提示`deploy files successfully`的，当我配置rootDir为build的时候报警信息是`no files to inspect`。
could u pls help me with it~

**Comment by qiu8310** [comment]
你把你的配置发一下

**Comment by cdll** [comment]
这个问题解决了，谢谢～我之前`yourTarget`数组写的空数组的，我以为要处理的文件是传入`includes`数组～

**Comment by qiu8310** [comment]
客气～
