### ISSUE TITLE
how could i ignore the linked href url in html?

### ISSUE THREAD

**Issue by cdll** [qiu8310/grunt-deploy-asset#2]
`zzz.html`页面中有`<a href='/xxx/yyy.html'>`时报错

```
ERR! file not exists /xxx/yyy.html in zzz.html at 1183
ERR! use force option to proceed 
Fatal error: Error: File /xxx/yyy.html not exists
```

主要是因为我这里做了不少nginx重定向了`/xxx_yyy.html`文件，有办法解决这个问题么？

**Comment by qiu8310** [comment]
你可以全局安装 [deploy-asset](https://github.com/Hujiang-FE/deploy-asset) ，使用命令行去上传，命令行支持忽略这种错误，你现在用的 grunt 插件都很老了，我都不更新了

**Comment by cdll** [comment]
@qiu8310 好吧，谢谢。弃坑了～
